---
- connection: local
  hosts: localhost
  gather_facts: false
  vars_files:
  - ../vars/shared_vars.yml
  tasks:
  - name: Setup module04
    include_role:
      name: avinetworks.aviconfig
    vars:
      avi_config_file: "{{ module_name }}"
    loop:
      - "module04-00.yml"
      - "module04-01.yml"
      - "module04-02.yml"
      - "module04-03.yml"
      - "module04-04.yml"
      - "module04-05.yml"
      - "module04-06.yml"
      - "module04-07.yml"
      - "module04-08.yml"
      - "module04-09.yml"
      - "module04-10.yml"
      - "module04-11.yml"
      - "module04-12.yml"
    loop_control:
      loop_var: module_name